version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: root
      POSTGRES_DB: employee_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080 

volumes:
  postgres_data: 
